//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM31.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\AionRun47\\AC-Game")]
        public string gamePath {
            get {
                return ((string)(this["gamePath"]));
            }
            set {
                this["gamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\AionRun47\\AC-Login")]
        public string loginPath {
            get {
                return ((string)(this["loginPath"]));
            }
            set {
                this["loginPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\AionRun47\\AC-Chat")]
        public string chatPath {
            get {
                return ((string)(this["chatPath"]));
            }
            set {
                this["chatPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string webHost {
            get {
                return ((string)(this["webHost"]));
            }
            set {
                this["webHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int webPort {
            get {
                return ((int)(this["webPort"]));
            }
            set {
                this["webPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int runMode {
            get {
                return ((int)(this["runMode"]));
            }
            set {
                this["runMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-Xms128m -Xmx128m -Xdebug -Xrunjdwp:transport=dt_socket,address=8997,server=y,sus" +
            "pend=n -ea -cp ./libs/*;ac-chat.jar com.aionemu.chatserver.ChatServer")]
        public string argsChatMode1 {
            get {
                return ((string)(this["argsChatMode1"]));
            }
            set {
                this["argsChatMode1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-Xms64m -Xmx64m -server -cp ./libs/*;ac-chat.jar com.aionemu.chatserver.ChatServe" +
            "r")]
        public string argsChatMode2 {
            get {
                return ((string)(this["argsChatMode2"]));
            }
            set {
                this["argsChatMode2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-Xms32m -Xmx32m -Xdebug -Xrunjdwp:transport=dt_socket,address=8999,server=y,suspe" +
            "nd=n -ea -cp ./libs/*;ac-login.jar com.aionemu.loginserver.LoginServer")]
        public string argsLoginMode1 {
            get {
                return ((string)(this["argsLoginMode1"]));
            }
            set {
                this["argsLoginMode1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-Xms64m -Xmx64m -server -cp ./libs/*;ac-login.jar com.aionemu.loginserver.LoginSe" +
            "rver")]
        public string argsLoginMode2 {
            get {
                return ((string)(this["argsLoginMode2"]));
            }
            set {
                this["argsLoginMode2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-Xms512m -Xmx%MEMSIZE%m -XX:-UseSplitVerifier -XX:+TieredCompilation -Xdebug -Xru" +
            "njdwp:transport=dt_socket,address=8998,server=y,suspend=n -ea -javaagent:./libs/" +
            "ac-commons-1.3.jar -cp ./libs/*;AC-Game.jar com.aionemu.gameserver.GameServer")]
        public string argsGameMode1 {
            get {
                return ((string)(this["argsGameMode1"]));
            }
            set {
                this["argsGameMode1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-Xms512m -Xmx%MEMSIZE%m -XX:-UseSplitVerifier -XX:+TieredCompilation  -server -ea" +
            " -javaagent:./libs/ac-commons-1.3.jar -cp ./libs/*;AC-Game.jar com.aionemu.games" +
            "erver.GameServer")]
        public string argsGameMode2 {
            get {
                return ((string)(this["argsGameMode2"]));
            }
            set {
                this["argsGameMode2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8192")]
        public int gameMemSize {
            get {
                return ((int)(this["gameMemSize"]));
            }
            set {
                this["gameMemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\AionRun47")]
        public string serverBase {
            get {
                return ((string)(this["serverBase"]));
            }
            set {
                this["serverBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***")]
        public string javaHome {
            get {
                return ((string)(this["javaHome"]));
            }
            set {
                this["javaHome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.2.0")]
        public string version {
            get {
                return ((string)(this["version"]));
            }
            set {
                this["version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public long maxToll {
            get {
                return ((long)(this["maxToll"]));
            }
            set {
                this["maxToll"] = value;
            }
        }
    }
}
